# Generated by Django 4.1 on 2022-08-20 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Brand name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Brand Image')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Category name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Category Image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Prod name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Prod Image')),
                ('price', models.IntegerField(verbose_name='Prod price')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodbrand', to='main.brand')),
            ],
            options={
                'verbose_name': 'Prod',
                'verbose_name_plural': 'Prods',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catbrand', to='main.category'),
        ),
    ]
